
title: QuickTheories
url: "http://quicktheories.org"
description: QuickTheories - property based testing for Java 8
twitter_username: 0hjc
github_username:  NCR-CoDE/QuickTheories

# Build settings
markdown: kramdown


